name: Copy Files from master to master-to-gh-action

on:
  push:
    branches:
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          # By default, actions/checkout checks out all files in the branch that
          # triggered the workflow, but you only requested the master branch here.
      
      - name: Create master-to-gh-action branch if it doesn't exist
        run: |
          git branch | grep -q "master-to-gh-action" || git branch -M master-to-gh-action
      
      - name: Copy files from master to master-to-gh-action
        run: |
          # Recursively copy non-existing files only
          cp -rni master/* master-to-gh-action/
          
          # Add new files to the index
          cd master-to-gh-action
          git add .
          
          # Commit the changes to the master-to-gh-action branch
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git commit -m "Copy files from master branch"
          git push origin master-to-gh-action
