name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary folder
        run: |
          mkdir ../tmp111
          ls -a

      - name: Copy files to temporary folder
        run: cp -r * ../tmp111/

      - name: Switch to gh_action_branch branch
        run: |
          git checkout -b gh_action_branch
          ls -a
          

      - name: Copy files from temporary folder to gh_action_branch branch root
        run: |
          cp -r ../tmp111/* ./
          ls -a
          git status

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Configure Pages
        uses: actions/configure-pages@v2

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: '.vitepress/dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_action_branch
          artifact: pages
